
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/s27 

module s27(CK, CLR, G0, G1, G17, G2, G3);
  input CK, CLR, G0, G1, G2, G3;
  output G17;
  wire CK, CLR, G0, G1, G2, G3;
  wire G17;
  wire G5, G6, G7, UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_10;
  DFF_X1 DFF_0_Q_reg(.CK (CK), .D (n_10), .Q (G5), .QN (UNCONNECTED));
  AND3_X1 g182(.A1 (CLR), .A2 (G0), .A3 (G17), .ZN (n_10));
  DFF_X1 DFF_1_Q_reg(.CK (CK), .D (n_8), .Q (G6), .QN (UNCONNECTED0));
  AND2_X1 g183(.A1 (CLR), .A2 (n_7), .ZN (n_8));
  INV_X1 g185(.A (n_7), .ZN (G17));
  NOR2_X1 g186(.A1 (G5), .A2 (n_6), .ZN (n_7));
  DFF_X1 DFF_2_Q_reg(.CK (CK), .D (n_5), .Q (G7), .QN (UNCONNECTED1));
  AND2_X1 g187(.A1 (n_2), .A2 (n_4), .ZN (n_6));
  NOR3_X1 g188(.A1 (n_0), .A2 (G2), .A3 (n_3), .ZN (n_5));
  NAND2_X1 g189(.A1 (G3), .A2 (n_3), .ZN (n_4));
  NAND2_X1 g190(.A1 (G6), .A2 (n_1), .ZN (n_2));
  NOR2_X1 g191(.A1 (G1), .A2 (G7), .ZN (n_3));
  INV_X1 g192(.A (G0), .ZN (n_1));
  INV_X1 g193(.A (CLR), .ZN (n_0));
endmodule

